Created .snyk ignore policy file
DelineaXPM/dsv-azure-pipelines-task pull request #60
Opened 2024-08-01 16:03 UTC by pacificcode

created .snyk policy. Added policy to ignore vendor/ and .devcontainer/ directories.

2024-08-01 16:14 UTC, sheldonhull requested changes
this should help i think with local IDE tooling, but it won't stop the PR checks from flagging. They don't honor this file last I checked for opensource checks, license at least. Is this the goal?

2024-08-01 16:19 UTC, pacificcode commented
@sheldonhull the .snyk file was added to the dsv-cli repo and Snyk no longer reports issues with the vendor/ directory code.
See report here: https://app.snyk.io/org/devops-secrets-vault/project/19dc579a-7e13-4b98-8a4f-5546aff44f4e

Adding this file to this repo looking for the same results.

2024-08-01 17:26 UTC, pacificcode commented
> this should help i think with local IDE tooling, but it won't stop the PR checks from flagging. They don't honor this file last I checked for opensource checks, license at least. Is this the goal?

This process worked very nicely for the gitlab repo as well. If we can resolve this and get it merged that would be very helpful.

2024-08-07 19:26 UTC, sheldonhull approved these changes

2024-08-07 19:37 UTC, merged